// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaDZZeFtvOM0sKTCQSNVHN6r82Qoi8shk',
    appId: '1:297242846003:web:1244552fcb33fe20a49446',
    messagingSenderId: '297242846003',
    projectId: 'chess-game-5fafd',
    authDomain: 'chess-game-5fafd.firebaseapp.com',
    storageBucket: 'chess-game-5fafd.firebasestorage.app',
    measurementId: 'G-L35G8HK1N1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8mWJkiTYLkgIJUiC8lrrw4WErVPrnKc',
    appId: '1:297242846003:android:1aa0096eed7a5d03a49446',
    messagingSenderId: '297242846003',
    projectId: 'chess-game-5fafd',
    storageBucket: 'chess-game-5fafd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2y9zEzBm0XLJ5Uf-pRY4X3lbNparJ6RA',
    appId: '1:297242846003:ios:08b5ae79a691a9fea49446',
    messagingSenderId: '297242846003',
    projectId: 'chess-game-5fafd',
    storageBucket: 'chess-game-5fafd.firebasestorage.app',
    iosBundleId: 'com.example.chessGame',
  );

}